[project]
name = "ceia-vpc1"
version = "0.1.0"
description = "CEIA - Visión por Computadora 1"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
    "supervision>=0.25.1",
]
